--- 
artifacts: 
  files: 
    - 'appspec.yml'
  type: zip
phases: 
  install: 
    commands: 
      - "echo start"
      - pwd
      - "echo setting up front-end variables"
      - echo REACT_APP_FIREBASE_API_KEY=\"$REACT_APP_FIREBASE_API_KEY\" >>.env
      - echo REACT_APP_FIREBASE_AUTH_DOMAIN=\"$REACT_APP_FIREBASE_AUTH_DOMAIN\" >>.env
      - echo REACT_APP_FIREBASE_PROJECT_ID=\"$REACT_APP_FIREBASE_PROJECT_ID\" >>.env
      - pwd
      - "npm install"
      - pwd
      - "npm run build"
version: 0.2
