version: 0.2

# This spec prepares a production-ready bundle to distribute through Cloudfront.

phases:
  build:
    commands:
      - pwd
      - "yarn install"
      - "yarn build"

artifacts:
  files:
    - "**/*"
  base-directory: "build"
